### ISSUE TITLE
Name the project

### ISSUE THREAD

**Issue by arieljannai** [arieljannai/hackbgu2020#1]
צריכים לחשוב על שם :)

תצביעו לאפשרויות שנראות לכם 👍 👎

**Comment by arieljannai** [comment]
meetina

**Comment by arieljannai** [comment]
@arieljannai meetux

**Comment by arieljannai** [comment]
meeten
![image](https://user-images.githubusercontent.com/3811594/93024771-7ebdf580-f601-11ea-9933-49322965f6a6.png)

**Comment by arieljannai** [comment]
@arieljannai connectsly

**Comment by arieljannai** [comment]
ketemu
![image](https://user-images.githubusercontent.com/3811594/93024761-69e16200-f601-11ea-83b5-2d36afcbc693.png)

**Comment by arieljannai** [comment]
enmeet
![image](https://user-images.githubusercontent.com/3811594/93024780-91382f00-f601-11ea-8241-1bd4c4fbfba4.png)

**Comment by arieljannai** [comment]
הרבה שמות על בסיס מיט, עם סיומות שונות
http://www.naminum.com/append?q=meet&s=Project

**Comment by danieljannai** [comment]
#meetU

**Comment by danieljannai** [comment]
unimeet
